name: axe-test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v2
    - name: Use NodeJS 16
      uses: action/setup-node@v1
      with:
        node-version: 16
    - run: npm ci
    - run: npm run build --if-present
    - run: npm start & npx wait-on https://localhost:3000
    - name: Run Axe
    - run: |
        npm install -g @axe-core/cli
        axe https://localhost:3000 --exit
    
  
