name: pa11y-test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use NodeJS 18
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - run: npm ci
    - run: npm run build --if-present
    - run: npm start & npx wait-on http://localhost:3000
    - name: Run Pa11y
      run: |
        npm install -g pa11y
        pa11y http://localhost:3000 --exit
